In [2]:
import numpy as np

In [3]:
arr = np.array([2,4,6,8,10])
add_arr = arr + 2
product_arr = arr*3
divide_arr = arr/2
print(add_arr)
print(product_arr)
print(divide_arr)

[ 4  6  8 10 12]
[ 6 12 18 24 30]
[1. 2. 3. 4. 5.]


In [4]:
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])

[5 4 6 3 2 1]


In [5]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
values , count = np.unique(x, return_counts=True)
max = np.max(count)
most_frequent = values[count == max]
print("Most Frequent value :",most_frequent)
print("Most Frequent indices:", np.where(x == most_frequent)[0])

Most Frequent value : [1]
Most Frequent indices: [0 5 7 8 9]


In [6]:
y = np.array([1,1,1,2,3,4,2,4,3,3])

In [7]:
values , count = np.unique(y, return_counts=True)
max = np.max(count)
most_frequent = values[count == max]
print("Most Frequent value :",most_frequent)
print("Most Frequent indices:", np.where(np.isin(y, most_frequent))[0])

Most Frequent value : [1 3]
Most Frequent indices: [0 1 2 4 8 9]


In [8]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)
print(arr[0][1])
print(arr[2][0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
20
70


In [ ]:
Mehul = np.linspace(10, 100, 25,dtype=int)

In [ ]:
print("Array:", Mehul)
transpose = Mehul.reshape(25,1)
print(transpose)
print(transpose.shape)

transpose_T = Mehul.reshape(25,1).T
print(transpose_T)
print(transpose_T.shape)

Array: [ 10  13  17  21  25  28  32  36  40  43  47  51  55  58  62  66  70  73
  77  81  85  88  92  96 100]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: int64
Total bytes: 200
[[ 10]
 [ 13]
 [ 17]
 [ 21]
 [ 25]
 [ 28]
 [ 32]
 [ 36]
 [ 40]
 [ 43]
 [ 47]
 [ 51]
 [ 55]
 [ 58]
 [ 62]
 [ 66]
 [ 70]
 [ 73]
 [ 77]
 [ 81]
 [ 85]
 [ 88]
 [ 92]
 [ 96]
 [100]]
(25, 1)
[[ 10  13  17  21  25  28  32  36  40  43  47  51  55  58  62  66  70  73
   77  81  85  88  92  96 100]]
(1, 25)


43.333333333333336
37.5
90
10
520


[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


[[10 20 30]
 [40 50 60]]
